config/routes.rb
Rails.application.routes.draw do
  get 'reservations/create'
  get 'photos/destroy'
  get 'rooms/index'
  get 'users/show'
  devise_for :users, :path=>'',
                    :path_names=>{:sign_in=>'login', :sign_out=>'logout', :edit=>'profile'},
                    :controllers=>{:registrations=>'registrations',
                                    :confirmations=>'confirmations',
                                    :omniauth_callbacks => "omniauth_callbacks"
                                  } 
  root 'pages#home'
  resources :users, only:[:show]
  resources :rooms, path: 'listings' do
    resources :reservations, only:[:create]
    resources :reviews, only: [:create, :destroy]
  end
  resources :photos

  resources :conversations, only: [:index, :create] do
    resources :messages, only: [:index, :create]
  end

  get '/preload' => 'reservations#preload'
  get '/preview' => 'reservations#preview'
  get 'my_trips' => 'reservations#your_trips', as: :your_trips
  get 'my_reservations' => 'reservations#your_reservations', as: :your_reservations
  get '/search' => 'pages#search'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/reservation.rb
class Reservation < ApplicationRecord
  belongs_to :user
  belongs_to :room

  has_one :payment
  accepts_nested_attributes_for :payment
end

app/controllers/reservations_controller.rb
class ReservationsController < ApplicationController
  before_action :authenticate_user!
  
  def preload
    room = Room.find(params[:room_id])
    today = Date.today
    reservations = room.reservations.where("start_date >= ? OR end_date >= ?", today, today)
    
    render json: reservations
 end
 
 def preview
     start_date = Date.parse(params[:start_date])
     end_date = Date.parse(params[:end_date])
     
     output = {
         conflict: is_conflict(start_date, end_date)
     }
     
     render json: output
 end

  def create
    @reservation = current_user.reservations.create(reservation_params)
    
    if @reservation.persisted?
      @payment = Payment.new({email: User.find(@reservation.user_id).email,
        token: params[:payment][:token], reservation_id: @reservation_id,
        amount: @reservation.total
      })

      begin
        result = @payment.process_payment

        if result.status == "succeeded"
          p result
          AppMailer.new_reservation(Room.find(@reservation.room_id), @reservation).deliver_now
          redirect_to @reservation.room, notice: "Reservation accepted!"
        end

      rescue Exception
        puts 'Payment failed!'
        redirect_to @reservation.room, notice:"Your payment was rejected"
      end
    end
  end
 
  def your_trips
    @trips = current_user.reservations
  end

  def your_reservations
    @rooms = current_user.rooms
  end

  private 
  def reservation_params
    params.require(:reservation).permit(:start_date, :end_date, :price, :total, :room_id, :payment)
  end

  def is_conflict(start_date, end_date)
    room = Room.find(params[:room_id])
    check = room.reservations.where("? < start_date AND end_date < ?", start_date, end_date)
    check.size > 0 ? true : false
  end
end

app/helpers/reservations_helper.rb
module ReservationsHelper
end

app/views/reservations/_form.html.erb
<%= form_for([@room, @room.reservations.new], html: {class:'cc_form'}) do |f| %>
    
    <div class="row">
        <div class="col-md-12 price_tag">
            <span>$<%= @room.price %></span>
            <span class="pull-right">Per night</span>
        </div>
    </div>
    
    <div class="row">
        <div class="col-md-6">
            <label>Arrival</label>
            <%= f.text_field :start_date, readonly: 'true', placeholder: 'mm/dd/yyyy', class: 'form-control' %>
        </div>

         <div class="col-md-6">
            <label>Departure</label>
            <%= f.text_field :end_date, readonly: 'true', placeholder: 'mm/dd/yyyy', class: 'form-control', disabled: 'true' %>
        </div>
    </div>

    <h5> <div id="message"></div> </h5>

    <div id="preview" style="display: none">
        <table class="reservation-table">
            <tbody>
                <tr>
                    <td>Night(s)</td>
                    <td><span id="reservation_days"></span></td>
                </tr>
                <tr>
                    <td>Total</td>
                    <td><span id="reservation_sum"></span></td>
                </tr>
            </tbody>
        </table>
        <br>
        <div id="card-elem"></div>
        <h5><span id="stripe"></span></h5>
        <% fields_for(:payment) do |p| %>
            <div class="row">
                <div class="col-md-12">
                    <div class="row">
                        <div class="form-group col-md-8">
                            <%= p.label :card_number, "Card Number", data: { stripe: 'label' } %>
                            <%= p.text_field :card_number, class:"form-control", required: true, data: {stripe: 'number' } %>
                        </div>
                        <div class="form-group col-md-4">
                            <%= p.label :card_cvv, "CVV", data: {stripe: 'label' } %>
                            <%= p.text_field :card_cvv, class:"form-control", required: true, data: {stripe: 'cvv' } %>
                        </div>
                    </div>
                    <div class="col-md-10">
                        <div class="row">
                            <div class="col-md-12">
                                <%= p.label :card_expires, "Expiry Date:", data: {stripe: 'label'} %>
                            </div>
                            <div class="form-group col-md-5">
                                <%= p.select :card_expires_month, options_for_select(Payment.month_options), {include_blank: 'Month'}, "data-stripe" => "exp-month", class:"form-control", required: true %>
                            </div>
                            <div class="form-group col-md-6">
                                <%= p.select :card_expires_year, options_for_select(Payment.year_options.push), {include_blank: 'Year'}, class:"form-control", data: {stripe: "exp-year"}, required: true %>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        <% end %>
    </div>

    <%= f.hidden_field :room_id, value: @room.id %>
    <%= f.hidden_field :price, value: @room.price %>
    <%= f.hidden_field :total, id:'reservation_total' %>

    <br>
    
    <%= f.submit "Request a reservation", id: "btn_book", class: "btn btn-primary wide", disabled: 'true' %>
<% end %>

<script>
    function unavailable(date){
        mdy = (date.getMonth()+ 1) + "-" + date.getDate() + "-" + date.getFullYear();
        return[$.inArray(mdy, unavailableDates) == -1];
    }

    $(function(){

        unavailableDates = [];

        $.ajax({
            url: '/preload',
            data: {'room_id': <%= @room.id %> },
            dataType: 'json',
            success: function(data) {
                $.each(data, function(arrID, arrValue){
                    for(var d = new Date(arrValue.start_date); d <= new Date(arrValue.end_date); d.setDate(d.getDate() +1)) {
                        unavailableDates.push($.datepicker.formatDate('m-d-yy', d));
                    }
                })

                $('#reservation_start_date').datepicker({
                    dateFormat: 'yy-mm-dd',
                    minDate: 0,
                    maxDate: '3m',
                    beforeShowDay: unavailable,
                    onSelect: function(selected) {
                        var newdate = new Date($("#reservation_start_date").datepicker("getDate"));
                        newdate.setDate(newdate.getDate() + 1);
                        $('#reservation_end_date').datepicker("option", "minDate", newdate);
                        $('#reservation_end_date').attr('disabled', false);

                        var start_date = $(this).datepicker('getDate');
                        var end_date = $('#reservation_end_date').datepicker('getDate');
                        var diff = (end_date - start_date)/1000/60/60/24;
                        var days = Math.round(diff);

                        var input = {
                            'start_date': start_date,
                            'end_date': end_date,
                            'room_id': <%= @room.id %>
                        } 

                        $.ajax({
                            url: '/preview',
                            data: input,
                            success: function(data) {
                                if (data.conflict) {
                                    $('#message').show();
                                    $('#message').text("these dates are unavailable");
                                    $('#preview').hide();
                                    $('#btn_book').attr('disabled', true);
                                } else {
                                    $('#message').hide();
                                    $('#preview').show();
                                    $('#btn_book').attr('disabled', false);

                                    var total = days * <%= @room.price %>
                                    $('#reservation_days').text(days);
                                    $('#reservation_sum').text(total);
                                    $('#reservation_total').val(total);
                                }
                            }
                        });
                    }
                });

                $('#reservation_end_date').datepicker({
                    dateFormat: 'yy-mm-dd',
                    minDate: 0,
                    maxDate: '3m',
                    beforeShowDay: unavailable,
                    onSelect: function(selected) {
                        $('#reservation_start_date').datepicker("option", "maxDate", selected);

                        var start_date = $('#reservation_start_date').datepicker('getDate');
                        var end_date = $(this).datepicker('getDate');
                        var diff = (end_date - start_date)/1000/60/60/24;
                        var days = Math.round(diff);

                        var input = {
                            'start_date': start_date,
                            'end_date': end_date,
                            'room_id': <%= @room.id %>
                        } 

                            $.ajax({
                                url: '/preview',
                                data: input,
                                success: function(data) {
                                    if (data.conflict) {
                                        $('#message').show();
                                        $('#message').text("these dates are unavailable");
                                        $('#preview').hide();
                                        $('#btn_book').attr('disabled', true);
                                    } else {
                                        $('#message').hide();
                                        $('#preview').show();
                                        $('#btn_book').attr('disabled', false);

                                        var total = days * <%= @room.price %>
                                        $('#reservation_days').text(days);
                                        $('#reservation_sum').text(total);
                                        $('#reservation_total').val(total);
                                    }
                                }
                            });
                        
                    }
                });
        }
        });

      
    });
</script>

<script language="Javascript">
    Stripe.setPublishableKey("pk_test_igIkCNVkhrHRBDZx8jdVhkle");

</script>

<script>
    let stripe = Stripe('pk_test_igIkCNVkhrHRBDZx8jdVhkle');
    let elements = stripe.elements();
    let style = {
        base: {
            // Add your base input styles here. For example:
            fontSize: '16px',
            color: "#32325d",
        }
    };
    let card = elements.create('card', {style: style});
    card.mount('#card-elem')
    $('.cc_form').on('submit', function(e){
        e.preventDefault()
        stripe.createToken(card).then(function(result){
            let form = document.querySelector('.cc_form')
            let hidden = document.createElement("input")
            hidden.setAttribute("type", "hidden")
            hidden.setAttribute("name", "payment[token]")
            hidden.setAttribute("value", result.token.id)
            form.appendChild(hidden)
            form.submit()
        })
    })
</script>

app/views/reservations/your_reservations.html.erb
<div class="row">
    <div class="col-md-3">
        <ul class=sidebar-list>
            <li class="sidebar-item"> <%= link_to "My listings", rooms_path, class:"sidebar-link" %> </li>
            <li class="sidebar-item"> <%= link_to "My reservations", your_reservations_path, class:"sidebar-link active" %> </li>
            <li class="sidebar-item"> <%= link_to "My trips", your_trips_path, class:"sidebar-link" %> </li>
        </ul>
    </div>
    <div class="col-md-9">
        <div class="panel panel-default">
            <div class="panel-heading">My reservations</div>
            <div class="panel-body">
                <% @rooms.each do |room| %>
                    <% room.reservations.order("id DESC").each do |reservation| %>
                        <div class="row">
                            <div class="col-md-2"> 
                                From <%= reservation.start_date.strftime('%m.%d.%y') %> to <%= reservation.end_date.strftime('%m.%d.%y') %>
                            </div>
                            <div class="col-md-6">
                                <%= link_to room_path(reservation.room) do %>
                                    <%= image_tag reservation.room.photos[0].image.url(:thumb) if reservation.room.photos.length > 0 %>
                                <% end %>
                            </div>
                            <div class="col-md-2">
                                <%= link_to user_path(reservation.room.user) do %>
                                    <%= image_tag avatar_url(reservation.user), class: "rounded-circle avatar-medium" %>
                                <% end %>
                            </div>
                            <div class="col-md-2 right">
                                <h4> <%= reservation.total %> $</h4>
                            </div>
                        </div>
                        <hr>
                    <% end %>
                <% end %>
            </div>
        </div>
    </div>
</div>

app/views/reservations/your_trips.html.erb
<div class="row">
    <div class="col-md-3">
        <ul class=sidebar-list>
            <li class="sidebar-item"> <%= link_to "My listings", rooms_path, class:"sidebar-link" %> </li>
            <li class="sidebar-item"> <%= link_to "My reservations", your_reservations_path, class:"sidebar-link" %> </li>
            <li class="sidebar-item"> <%= link_to "My trips", your_trips_path, class:"sidebar-link active" %> </li>
        </ul>
    </div>
    <div class="col-md-9">
        <div class="panel panel-default">
            <div class="panel-heading">My trips</div>
            <div class="panel-body">
                <% @trips.order("id DESC").each do |trip| %>
                <div class="row">
                    <div class="col-md-2"> 
                        From <%= trip.start_date.strftime('%m.%d.%y') %> to <%= trip.end_date.strftime('%m.%d.%y') %>
                    </div>
                    <div class="col-md-6">
                        <%= link_to room_path(trip.room) do %>
                            <%= image_tag trip.room.photos[0].image.url(:thumb) if trip.room.photos.length > 0 %>
                        <% end %>
                    </div>
                    <div class="col-md-2">
                        <%= link_to user_path(trip.room.user) do %>
                            <%= image_tag avatar_url(trip.room.user), class: "rounded-circle avatar-medium" %>
                        <% end %>
                    </div>
                    <div class="col-md-2 right">
                        <h4> <%= trip.total %> $</h4>
                    </div>
                </div>
                <hr>
            <% end %>
            </div>
        </div>
    </div>
</div>