config/routes.rb
Rails.application.routes.draw do
  get 'reservations/create'
  get 'photos/destroy'
  get 'rooms/index'
  get 'users/show'
  devise_for :users, :path=>'',
                    :path_names=>{:sign_in=>'login', :sign_out=>'logout', :edit=>'profile'},
                    :controllers=>{:registrations=>'registrations',
                                    :confirmations=>'confirmations',
                                    :omniauth_callbacks => "omniauth_callbacks"
                                  } 
  root 'pages#home'
  resources :users, only:[:show]
  resources :rooms, path: 'listings' do
    resources :reservations, only:[:create]
    resources :reviews, only: [:create, :destroy]
  end
  resources :photos

  resources :conversations, only: [:index, :create] do
    resources :messages, only: [:index, :create]
  end

  get '/preload' => 'reservations#preload'
  get '/preview' => 'reservations#preview'
  get 'my_trips' => 'reservations#your_trips', as: :your_trips
  get 'my_reservations' => 'reservations#your_reservations', as: :your_reservations
  get '/search' => 'pages#search'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/_navigation.html.erb
<nav class="navbar fixed-top navbar-expand-lg navbar-light bg-light">
    <a class="navbar-brand" <%= link_to 'Flairbnb', root_path %></a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    

    <div class="collapse navbar-collapse" id="navbarSupportedContent">

        <%= form_tag search_path, class: "navbar-form navbar-left", method: :get do %>
 
            <div class="search">
                <i class="fa fa-search"></i>
                <%= text_field_tag :search, params[:search], placeholder: "search", class: "form-control" %>
            </div>
        
        <% end %>

        <ul class="navbar-nav ml-auto">
            <li>
                <a class="nav-link" <%= link_to new_room_path do %>
                    <i class="fa fa-home fa-lg"></i> Become a host
                <% end %>
                </a>
            </li>

            <li>
                <a class="nav-link" <%= link_to conversations_path do %>
                    Messages
                <% end %>
                </a>
            </li>

            <% if (!user_signed_in?) %>
                <a class="nav-link"<%= link_to 'Signup', new_user_registration_path %></a>
                <a class="nav-link"<%= link_to 'Signin', new_user_session_path %></a>
            <% else %>

            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    <%= image_tag avatar_url(current_user), class: "rounded-circle avatar-small" %> <%= current_user.fullname %>
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                    <a class="dropdown-item"<%= link_to 'My listings', rooms_path %> </a>
                    <a class="dropdown-item"<%= link_to 'My reservations', your_reservations_path %> </a>
                    <a class="dropdown-item"<%= link_to 'My trips', your_trips_path %> </a>
                    <a class="dropdown-item" <%= link_to 'Edit my profile', edit_user_registration_path %></a>

                    
                    <div class="dropdown-divider"></div>
                    <a class="dropdown-item" <%= link_to 'Signout', destroy_user_session_path, method: :delete %></a>
                </div>
            </li>
            
            <% end %>
        </ul>

    </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Flairbnb</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://js.stripe.com/v3/"></script>
    <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
  </head>

  <body>
    <%= render partial: 'layouts/navigation' %>

    <%= render partial: 'shared/message'%>

    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>